name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"

jobs:
  tests:
    name: "CI"

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          # extensions: mongodb, redis, amqp

      - name: "Install latest dependencies"
        run: |
          composer update

      - name: "Run psalm"
        run: ./vendor/bin/psalm -c psalm.xml

      - name: "Run tests"
        run: "composer run-script test"
